### ISSUE TITLE
Failed to build BLOCK, Ubuntu 18.04, Unreal 4.21

### ISSUE THREAD

**Issue by mango009** [Microsoft/AirSim#1795] opened 2019-02-19 19:41 UTC
I'm getting a compile failed error while building block:

[2019.02.19-19.39.00:109][339]In file included from /home/mango/tools/AirSim/Unreal/Environments/Blocks 4.21/Plugins/AirSim/Intermediate/Build/Linux/B4D820EA/UE4Editor/Development/AirSim/Module.AirSim.cpp:2:
[2019.02.19-19.39.00:110][339]/home/mango/tools/AirSim/Unreal/Environments/Blocks 4.21/Plugins/AirSim/Source/AirBlueprintLib.cpp:127:42: error: no member named 'IncrementFlushOnDraw' in 'FSceneViewport'
[2019.02.19-19.39.00:110][339]            viewport->GetGameViewport()->IncrementFlushOnDraw();
[2019.02.19-19.39.00:110][339]            ~~~~~~~~~~~~~~~~~~~~~~~~~~~  ^
[2019.02.19-19.39.00:110][339]/home/mango/tools/AirSim/Unreal/Environments/Blocks 4.21/Plugins/AirSim/Source/AirBlueprintLib.cpp:134:42: error: no member named 'DecrementFlushOnDraw' in 'FSceneViewport'
[2019.02.19-19.39.00:110][339]            viewport->GetGameViewport()->DecrementFlushOnDraw();
[2019.02.19-19.39.00:110][339]            ~~~~~~~~~~~~~~~~~~~~~~~~~~~  ^
[2019.02.19-19.39.10:521][339]2 errors generated.
[2019.02.19-19.39.10:725][339]ERROR: UBT ERROR: Failed to produce item: /home/mango/tools/AirSim/Unreal/Environments/Blocks 4.21/Plugins/AirSim/Binaries/Linux/libUE4Editor-AirSim.so
[2019.02.19-19.39.10:725][339]       (see ../Programs/UnrealBuildTool/Log.txt for full exception trace)

**Comment by madratman** [comment] 2019-02-19 20:08
duplicate of #1657
unreal 4.21 removed the increment and decrement flushondraw api, causing this error, as explained here https://github.com/Microsoft/AirSim/issues/1657#issuecomment-457202356

I'd suggest switching to 4.18, or if that's not feasible, you can try the hack of removing these two lines directly as mentioned here https://github.com/Microsoft/AirSim/issues/1657#issuecomment-461697674, however we haven't tested this

**Closed by madratman** 2019-02-19 20:08 UTC
