### ISSUE TITLE
Laser Scanners

### ISSUE THREAD

**Issue by roaddy** [Microsoft/AirSim#674] opened 2017-12-10 14:14 UTC
Is there any plan about adding laser scanners into sensors?? Since it is an important sensor for autopilot system of cars @sytelus

**Comment by mitchellspryn** [comment] 2017-12-10 18:35
Duplicate of [this issue](https://github.com/Microsoft/AirSim/issues/621).

**Closed** 2017-12-11 06:43 UTC
