### ISSUE TITLE
Minimum requirements

### ISSUE THREAD

**Issue by sakaryag** [microsoft/AirSim#3047] opened 2020-09-28 15:38 UTC
Is there any minimum requirements for AirSim about graphics card?
I am opening UE4 editor but after loading process it automatically close itself without showing any error or sth. My Ram:8GB ; i7 CPU Quadcore 1.73 GHz ; graphics card: NVDIA GeG_Force GT 425M ; Ubuntu 16.04
What can be the problem? Can anybody help, please?

**Comment by jonyMarino** [comment] 2020-09-29 16:32
I don't think this is a hardware issue and I think it is a duplicate of #3041 please follow there.

**Closed by jonyMarino** 2020-09-29 16:32 UTC
