### ISSUE TITLE
#951 downloading rpclib：拒绝访问

### ISSUE THREAD

**Issue by XueYuSky** [Microsoft/AirSim#951] opened 2018-04-10 08:27 UTC
win10,VS2015 pro3,  cmake 3.9.3
when I run build.cmd,err occurs:

C:\Users\XueYuSky\source\repos\AirSim>build.cmd
Found cmake version: 3.9.6

*****************************************************************************************
Downloading rpclib
*****************************************************************************************
拒绝访问。
拒绝访问。
找不到 C:\Users\XueYuSky\source\repos\AirSim\external\rpclib.zip
Unable to download high-polycount SUV. Your AirSim build will use the default vehicle.

**Comment by XueYuSky** [comment] 2018-04-10 08:30
English:

C:\Users\XueYuSky\source\repos\AirSim>build.cmd
Found cmake version: 3.9.6

Downloading rpclib

 access denied.
 access denied.
Can't find  C:\Users\XueYuSky\source\repos\AirSim\external\rpclib.zip
Unable to download high-polycount SUV. Your AirSim build will use the default vehicle.

Build failed - see messages above.

**Comment by XueYuSky** [comment] 2018-04-10 09:16
reasong: I didn't restart my PC after I changed the enviroment variable.

I reboot my  computer and build again, it works. then encounter the half.h issues which someone have solve that problem.

**Comment by sytelus** [comment] 2018-04-12 01:12
I can't reproduce this issue. I'm guessing you have some permission issues. We'll close this issue for now.

**Closed by sytelus** 2018-04-12 01:12 UTC

**Comment by bys1123** [comment] 2018-04-12 04:10
Chinese Internet blocked rpclib download sometime.

**Comment by XueYuSky** [comment] 2018-04-15 09:31
Thank, I have solved this problem.

**Comment by hassanyf** [comment] 2018-06-20 11:10
How did you solve it?

**Comment by futuretx** [comment] 2019-01-11 12:52
I met the same err, would you show the reason?

**Comment by XueYuSky** [comment] 2019-01-23 01:36
> How did you solve it?



> How did you solve it?



> I met the same err, would you show the reason?
I used my sserver in Singapore,recompile it.

**Comment by calmelo** [comment] 2020-07-16 04:23
把杀毒软件关了就可以了
