### ISSUE TITLE
There is no termios module in Python of the windows version.

### ISSUE THREAD

**Issue by EvelynZhou** [Microsoft/AirSim#860] opened 2018-03-04 07:20 UTC
There is no termios module in Python of the windows version.

**Comment by sytelus** [comment] 2018-03-04 21:53
Please provide proper repro steps, error messages, config and your OS details.

**Comment by allen9273** [comment] 2018-03-14 15:01
i suggest you reference to #873 issue

**Comment by sytelus** [comment] 2018-03-15 02:09
Closing as duplicate of https://github.com/Microsoft/AirSim/issues/873.

**Closed** 2018-04-12 05:39 UTC
