### ISSUE TITLE
Will the hover mode be interrupted by the movebyvelocity() 

### ISSUE THREAD

**Issue by Rutsow** [microsoft/AirSim#2928] opened 2020-08-12 08:53 UTC
In SimpleFlight, I train a DQN model for the drone and the movebyvelocity() is used. But after the duration it shows that API call is not received, entering hover mode for safety. I tested the velocity after the movebyvelocity().join() finished, but the vx and vy is not 0. Is that right? And will the hover mode be interrupted by the next movebyvelocity() command?
I run it in Win10,python3.7, UE4.18

**Comment by zimmy87** [comment] 2021-01-07 18:53
Yes, what you're reporting is the expected behavior for the movebyvelocity() API and entering hover mode:

1. After the duration given in movebyvelocity() passes, the drone should enter hover mode
2. vx and vy are generally not expected to be 0 after a call to movebyvelocity().join() due to leftover inertia from the drone's movement
3. the hover mode will be interrupted by any new command to the drone

**Closed** 2021-03-22 21:26 UTC
Labels: question
