### ISSUE TITLE
StereoImageGenerator produces dark Stereo Images

### ISSUE THREAD

**Issue by EliteTUM** [Microsoft/AirSim#402] opened 2017-08-06 14:28 UTC
I ran **runSteroImageGenerator()** from the Example-StereoImage-Generator from [here](https://github.com/Microsoft/AirSim/blob/master/Examples/main.cpp) using the [Blocks-Environment](https://github.com/Microsoft/AirSim/tree/master/Unreal/Environments/Blocks).

In general, the communication works: Once I run SimpleFlight in the BlocksEnvironment, Startup the StereoImage-Generator-Example in another executable as RPC-Client and the Connection is established properly and the left, right and disparity Image are saved (in the example for Random Positions).

When watching the Images being generated in the Unreal Editor, they look allright and the Scene seems to have proper lighting. Although, when taking a look at the Stereoimages, they all seem to be too dark. Outlines can only be seen as black silhouettes. Any idea why? Do you have the same Problem?

See the example Images attached (left and right Image of same timestep):
![left_000037](https://user-images.githubusercontent.com/720488/29004203-1e6c8f68-7ac4-11e7-9eac-b8616ce6e625.png)
![right_000037](https://user-images.githubusercontent.com/720488/29004205-294e6d70-7ac4-11e7-9676-9bc859fb0c31.png)

**Comment by EliteTUM** [comment] 2017-08-06 14:32
OK this is strange. Now that I see the uploaded Images, they appear to be mostly ok. Indeed, they even seem too bright. Looks like this is a Problem with the Default Win10-Picture-Viewer. When opening the Pictures above they rather look like this on my Screen (Screenshot taken using Snipping Tool):

![screenshot](https://user-images.githubusercontent.com/720488/29004243-c9b5e3ec-7ac4-11e7-9031-0f86a6abbc32.PNG)

**Comment by EliteTUM** [comment] 2017-08-06 17:37
I just tested different Settings for Quality (Engine Scalability Settings) and the results look the same. Additionally, when taking Pictures by clicking the record button they do look exactly the same: no textures recognizable, only the Background in somewhat blue Color, all objects dark/black.

**Comment by sytelus** [comment] 2018-04-12 00:11
Closing this as duplicate of https://github.com/Microsoft/AirSim/issues/352

**Closed by sytelus** 2018-04-12 00:11 UTC
Labels: images
