### ISSUE TITLE
setting.json can not be changed(be rewritten everytime)  SOLVED.

### ISSUE THREAD

**Issue by allen9273** [Microsoft/AirSim#1066] opened 2018-05-07 05:50 UTC
The path of the setting.json is C:\Users\chen9\OneDrive\文档\AirSim.
win10 Home
vs2015 pro3
The problem is only produced in my laptop. My desktop is fine. No matter what I change in setting.json, whenever I run the binary (for example AirsimNH), it would be written as default value like this:
![image](https://user-images.githubusercontent.com/37375217/39686614-392aeefe-5209-11e8-8846-5c189e23f177.png)
Could anyone solve this problem?

**Comment by sytelus** [comment] 2018-05-08 22:36
I think this is probably happening due to asian characters in file path. Unfortunately we can't reproduce this issue on English versions. You can help s debug this, however. The relevant line of code is here:

https://github.com/Microsoft/AirSim/blob/7bddd5857791f9c164e8eba80c229f199c0babf8/Unreal/Plugins/AirSim/Source/SimHUD/SimHUD.cpp#L270

**Comment by allen9273** [comment] 2018-05-09 05:35
Thanks for your reply.  I have found the solution. Because of the Asian characters in file path, just right click on the "Documents"-"Properties" - "Location" , you will find the path content Asian characters. Just modify it to English, click on "OK". Everything will be fine.
![1](https://user-images.githubusercontent.com/37375217/39797213-1a7ecfc4-539a-11e8-86ee-766c37d4c67b.PNG)
![3](https://user-images.githubusercontent.com/37375217/39797215-1e3d7cfa-539a-11e8-8f04-ea9d4974eb43.PNG)

**Comment by sytelus** [comment] 2018-05-14 20:29
There might be side effect to this because you are renaming you document folder. For example, other applications which has set its path to location before you renamed might not work properly.

**Comment by Beijingsheng** [comment] 2018-08-08 07:47
This is the path of my settings.json C:\Users\risheng\Documents\AirSim. Still the problem exists.

**Comment by Beijingsheng** [comment] 2018-08-08 07:51
The Users folder is currently showing 用户, however it is Users when I check the path. I tried to change 用户 but it's a default folder and its name can't be changed.

**Comment by allen9273** [comment] 2018-08-08 08:02
![image](https://user-images.githubusercontent.com/37375217/43824283-b48c4cbc-9b30-11e8-8f78-af4219f025cb.png)
Can you copy your path  C:\Users\risheng\Documents\AirSim here and enter, check if the folder content settings?

**Comment by Beijingsheng** [comment] 2018-08-08 09:15
It works, in fact I just changed the display language from Chinese to English so I suppose there shouldn't be any Chinese character in the path?

**Comment by madratman** [comment] 2019-01-23 17:09
Yeah, chinese characters have caused errors reported in a few more issues as well. Let's stick to English. 
Closing this as it's resolved. please comment/re-open as needed.

**Closed by madratman** 2019-01-23 17:09 UTC
Labels: bug, help wanted

**Comment by damilolah** [comment] 2019-08-16 04:14
I use English and still have the same issue my file part is: C:\Users\4567\Documents\AirSim

Please help!!!

**Comment by allen9273** [comment] 2019-08-17 01:53
![image](https://user-images.githubusercontent.com/37375217/63205292-d6bfbb00-c0d4-11e9-96ce-89e9b3940110.png)
copy your path C:\Users\4567\Documents\AirSim here and enter, check if the folder content settings?

**Comment by andreasceid** [comment] 2021-05-16 21:29
Greek characters don't work too. That gives me an impression that all non Latin characters trigger this reset to the `settings.json` file. Path of `settings.json` file to simulate the problem was: `C:\Users\example_user\Έγγραφα`. The solution provided above applies for Greek characters, too.
