### ISSUE TITLE
Merging airsim game mode with other game modes

### ISSUE THREAD

**Issue by alvikag** [microsoft/AirSim#1127] opened 2018-05-30 06:40 UTC
Hi,
I am using to airsim for tracking applications which involves using a quadrotor and a ground rover simultaneously. Is there a way such that airsim and carsim can be used at the same time? 
In general, does airsim provide any gamemode merging/overlapping with another so as to have something like keyboard control of an unreal engine ground vehicle along with airsim quadrotor control. 

Thanks
Alvika

**Comment by DrifterFun** [comment] 2018-05-30 13:37
Hi I am now working to merge AirSim and CarSim. However I get some problem now. Maybe we can disscuss on this problem. You can get some information in following link.
[https://github.com/Microsoft/AirSim/issues/1077](url)

**Comment by kshitiz38** [comment] 2018-06-01 15:31
This is also referenced here #506.
You can check out my fork, I was able to achieve this by merging the two game modes.

**Comment by sytelus** [comment] 2018-06-23 04:06
We have done lots of refactoring recently which will make this possible much more cleanly and easily. Now car and multirotor APIs run on same port. Also, there is vehicle_name parameter in all relevant API calls.

**Comment by aadi-mishra** [comment] 2018-07-09 09:39
@sytelus But can you spawn a car and a multirotor with the new repo? I have seen multiple vehicles functionality but all of it seems for similar vehicles. Say multiple quadrotors or cars. Does this make it  possible to import and control both vehicles together? I am currently using Kshitiz's fork.

**Comment by RVBldr** [comment] 2018-10-19 18:14
This seems to be a duplicate of #1382.

**Comment by FL2316** [comment] 2019-05-27 01:09
I follow your advice, but there are some mistakes that can't be solved. I don't know what to do...seg fault,
Can anybody help me?thanks alot

**Closed** 2020-02-14 22:39 UTC
Labels: binary, closable, feature request
